# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        installation: ["lowest", "highest"]
        include:
        - python-version: 3.6
          installation: "lowest"

          NUMPY: "1.15.1"
          SCIKITLEARN: "0.22.0"
          SCIPY: "1.2.0"
          
        - python-version: 3.6
          installation: "highest"

          NUMPY: "1.19.5"
          SCIKITLEARN: "0.24.2"
          SCIPY: "1.6.3"

        - python-version: 3.7
          installation: "lowest"

          NUMPY: "1.15.1"
          SCIKITLEARN: "0.22.0"
          SCIPY: "1.2.0"
        
        - python-version: 3.7
          installation: "highest"

          NUMPY: "1.20.0"
          SCIKITLEARN: "0.24.2"
          SCIPY: "1.6.3"
          
        - python-version: 3.8
          installation: "lowest"

          # only starting from these version, there is a wheel
          NUMPY: "1.17.3"
          SCIKITLEARN: "0.22.0"
          SCIPY: "1.4.0"
        
        - python-version: 3.8
          installation: "highest"

          NUMPY: "1.20.0"
          SCIKITLEARN: "0.24.2"
          SCIPY: "1.6.3"  

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
         # Now downgrade packages if required by environment variables
        [ -z "${{matrix.NUMPY}}" ] || pip install numpy==${{matrix.NUMPY}}
        [ -z "${{matrix.SCIKITLEARN}}" ] || pip install scikit-learn==${{matrix.SCIKITLEARN}}
        [ -z "${{matrix.SCIPY}}" ] || pip install scipy==${{matrix.SCIPY}}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
